import './js/MobileFilter';
import './js/noUiRange';
import './js/onFirstRender';
import './js/closeAlert';
import './js/checkboxes';
import './js/mobileMenu';
import './js/productModal';
import './js/counter';
import './js/productsSlider';
